# Generated by Django 5.2.7 on 2025-10-15 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_publication_date_review_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='my_promotions_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.promotion', verbose_name='Мои акции'),
        ),
    ]
