# Generated by Django 5.2.7 on 2025-10-15 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_user_my_promotions_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='my_promotions_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.promotion', verbose_name='Мои акции'),
        ),
    ]
