# Generated by Django 5.2.7 on 2025-10-15 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_user_my_promotions_id_user_my_promotions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='my_promotions',
        ),
        migrations.AddField(
            model_name='user',
            name='my_promotions_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Мои акции'),
        ),
    ]
