# Generated by Django 5.2.7 on 2025-10-15 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_user_my_promotions_user_my_promotions_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='my_promotions_id',
        ),
        migrations.AddField(
            model_name='user',
            name='promotion_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.promotion', verbose_name='Акции'),
        ),
    ]
