# Generated by Django 5.2.7 on 2025-10-15 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_user_my_promotions_id_user_promotion_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cart_id',
        ),
    ]
