# Generated by Django 5.2.6 on 2025-10-16 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_user_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reviews_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.review', verbose_name='Отзывы'),
        ),
    ]
